# NOTE: This component MUST be used in the same OpenTofu stack (module directory)
# as eks-core-addons. The helm_release.argocd resource has:
#   depends_on = [aws_eks_addon.coredns]
# which references a resource generated by the eks-core-addons component.
# Both components land in the same provisioning stack so this cross-component
# reference resolves within a single tofu module — it is NOT a cross-stack reference.

generate_hcl "_tmgen-argocd-hub.tf" {
  # Conditional components are unsupported (SPIKE-FINDINGS: no ternary source, no
  # tm_dynamic "component"), so this component is always instantiated but emits
  # nothing unless enabled (bundle sets enabled = role=="hub").
  condition = component.input.enabled.value
  lets {
    local_env = component.input.account_map.value[component.input.env.value].endpoint != ""
    prefix    = component.input.project_prefix.value
    # Compute spoke ARN list at Terramate generate time.
    # [for e in spoke_envs : "arn:...account_map[e].account_id..."] evaluated
    # by Terramate since all data (spoke_envs, account_map) is available as
    # component inputs at generate time. Emitted as a literal list in the .tf.
    spoke_role_arns = [
      for e in component.input.spoke_envs.value :
      "arn:aws:iam::${component.input.account_map.value[e].account_id}:role/${component.input.project_prefix.value}-argocd-spoke-access"
    ]
  }
  content {
    # ---------------------------------------------------------------------------
    # ArgoCD controller IAM role — pod-identity trust (same pattern as ebs_csi).
    # ---------------------------------------------------------------------------
    resource "aws_iam_role" "argocd_controller" {
      name = "${let.prefix}-argocd-controller"
      assume_role_policy = jsonencode({
        Version = "2012-10-17"
        Statement = [{
          Effect    = "Allow"
          Principal = { Service = "pods.eks.amazonaws.com" }
          Action    = ["sts:AssumeRole", "sts:TagSession"]
        }]
      })
    }

    # Inline policy: allow controller to assume spoke-access roles in each spoke account.
    resource "aws_iam_role_policy" "argocd_assume_spokes" {
      name = "assume-spoke-access"
      role = aws_iam_role.argocd_controller.id
      policy = jsonencode({
        Version = "2012-10-17"
        Statement = [{
          Effect   = "Allow"
          Action   = "sts:AssumeRole"
          Resource = let.spoke_role_arns
        }]
      })
    }

    # ---------------------------------------------------------------------------
    # ArgoCD Helm release.
    # depends_on aws_eks_addon.coredns: that resource is generated by the
    # eks-core-addons component which MUST be co-located in this same stack.
    # ---------------------------------------------------------------------------
    resource "helm_release" "argocd" {
      name             = "argocd"
      namespace        = "argocd"
      create_namespace = true
      repository       = "https://argoproj.github.io/argo-helm"
      chart            = "argo-cd"
      version          = component.input.argocd_chart_version.value
      depends_on       = [aws_eks_addon.coredns]
    }

    # ---------------------------------------------------------------------------
    # Pod-identity associations — both ArgoCD SAs in the argocd namespace.
    # depends_on helm_release.argocd so the namespace + SA exist first.
    # ---------------------------------------------------------------------------
    # MiniStack does not implement CreatePodIdentityAssociation, and the IAM
    # role -> ServiceAccount binding is inert against its k3s cluster, so local
    # envs skip both associations. ArgoCD itself still installs and runs.
    tm_dynamic "resource" {
      for_each = let.local_env ? {} : {
        argocd_controller = "argocd-application-controller"
        argocd_server     = "argocd-server"
      }
      iterator = assoc
      labels   = ["aws_eks_pod_identity_association", assoc.key]
      attributes = {
        cluster_name    = component.input.cluster_name.value
        namespace       = "argocd"
        service_account = assoc.value
        role_arn        = tm_hcl_expression("aws_iam_role.argocd_controller.arn")
        depends_on      = tm_hcl_expression("[helm_release.argocd]")
      }
    }
  }
}
